# Generated by Django 5.1.7 on 2025-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_literal', models.CharField(max_length=15)),
            ],
        ),
    ]
