# Generated by Django 5.2.1 on 2025-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_vipstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipstatus',
            name='requierments',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
