# Generated by Django 5.2.1 on 2025-05-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achivments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchivmentsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('achivments_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='achivments.achivments')),
            ],
        ),
    ]
