# Generated by Django 5.1.7 on 2025-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('to_user', models.IntegerField()),
                ('subject', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
