# Generated by Django 5.1.7 on 2025-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_email',
            field=models.TextField(null=True),
        ),
    ]
