# Generated by Django 5.2 on 2025-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_level',
            field=models.BigIntegerField(default=0),
        ),
    ]
