# Generated by Django 5.1.7 on 2025-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
