# Generated by Django 5.2.1 on 2025-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_vip_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
