# Generated by Django 5.2.1 on 2025-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance_virtual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
