# Generated by Django 5.2.1 on 2025-05-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_balance_alter_user_balance_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance_virtual',
            field=models.FloatField(),
        ),
    ]
