# Generated by Django 5.1.7 on 2025-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_user_father_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Администратор'), ('1', 'Пользователь')], default='1', max_length=1, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(max_length=25, null=True, verbose_name='Отчество'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
