# Generated by Django 5.2 on 2025-05-19 10:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('end_date', models.DateTimeField()),
                ('prize_fund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('prize_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(70)])),
                ('base_fund', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('ticket_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('winner', 'Winner'), ('partial_winner', 'Partial Winner'), ('loser', 'Loser')], default='waiting', max_length=15)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lot.lottery')),
            ],
        ),
    ]
