# Generated by Django 5.2.1 on 2025-05-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
