# Generated by Django 5.2.1 on 2025-05-19 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0002_delete_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('ticket_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('winner', 'Winner'), ('partial_winner', 'Partial Winner'), ('loser', 'Loser')], default='waiting', max_length=15)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lot.lottery')),
            ],
        ),
    ]
