# Generated by Django 5.1.7 on 2025-05-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('author_email', models.TextField(max_length=50)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('payload', models.TextField(max_length=100)),
            ],
        ),
    ]
